### ISSUE TITLE
Прикрутить правильно настроенный checkstyle

### ISSUE THREAD

**Issue by mokevnin** [hexlet-basics/exercises-java#101]

**Comment by MisterCool** [comment]
А какие правила для чекстайла, кастомные сделать или взять гугловские?

**Comment by mokevnin** [comment]
А что считается прямо стандартом стандартом?

**Comment by MisterCool** [comment]
По дефолту берут sun_checks.xml
https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-checker-config.html
