### ISSUE TITLE
Странный вывод при использовании конструкции System.out.print

### ISSUE THREAD

**Issue by adslane** [hexlet-basics/exercises-java#195]
Если для вывода последней строки использовать конструкцию System.out.print("Renly"); без ln, то в выводе не будет строки с именем Renly
```
System.out.print("Robert");
System.out.print("Stannis");
System.out.print("Renly");
```
![image](https://user-images.githubusercontent.com/26318574/146595919-a5f94984-3497-4d23-a154-5c9ee5d5c05a.png)
![image](https://user-images.githubusercontent.com/26318574/146595950-b2059430-f24f-4ef4-9c5c-209da307ba94.png)

**Comment by Malcom1986** [comment]
Попробуйте в последнем вызове `System.out.print()` тоже добавить перевод строки и имя Renly появится:

```java
System.out.print("Robert\n");
System.out.print("Stannis\n");
System.out.print("Renly\n"); 
```

Если этого не сделать, то последняя строка перехватывается при тестировании консольного вывода

**Comment by ZhukovAlV** [comment]
не совсем понятно где проблема встречается, если в 1 задании https://ru.code-basics.test/languages/java/lessons/hello-world 
написать данный код:

class App {
    public static void main(String[] args) {
        // BEGIN (write your solution here)
        System.out.print("Robert\n"); 
        System.out.print("Stannis\n"); 
        System.out.print("Renly"); 
        // END
    }
}

То в выводк будет 3 строки:
Robert
Stannis
RenlyException in thread "main" java.lang.AssertionError: 
expected: "Hello, World!"
 but was: "Robert
Stannis
Renly"
	at Test.main(Test.java:19)
make: *** [Makefile:2: test] Error 1
#<Process::Status: pid 63 exit 2>
