### ISSUE TITLE
Прохождения теста при некорректном решении задания

### ISSUE THREAD

**Issue by kalapyha** [hexlet-basics/exercises-java#20]
![Screenshot from 2019-07-13 18-24-39](https://user-images.githubusercontent.com/47543543/61177152-38ec4400-a59c-11e9-83c9-11078c56938a.png)

**Comment by samokisha** [comment]
Не актуально.
![Снимок экрана 2019-07-16 в 21 19 16](https://user-images.githubusercontent.com/19905834/61319238-786e9680-a80f-11e9-984c-7105529a8197.png)

**Comment by mokevnin** [comment]
fixed!
