### ISSUE TITLE
Оператор конкатенации (замена "." на "+")

### ISSUE THREAD

**Issue by kalapyha** [hexlet-basics/exercises-java#21]
![Screenshot from 2019-07-13 19-09-17](https://user-images.githubusercontent.com/47543543/61177379-152bfc80-a5a2-11e9-83ce-16f747f517eb.png)

**Comment by mokevnin** [comment]
А вы можете прислать пулреквест?

**Comment by kalapyha** [comment]
Pull request has been sent. Thank you.
