### ISSUE TITLE
https://code-basics.com/ru/languages/java/lessons/operators#editor

### ISSUE THREAD

**Issue by FallenStarrr** [hexlet-basics/exercises-java#239]
В этом задании просят найти разность отрицательного числа но при этом тесты ждут сложения, никогда не видел чтобы отнимали отрицательные числа за свою работу

**Comment by ssssank** [comment]
@Malcom1986

**Comment by Malcom1986** [comment]
Вычитание из числа отрицательного числа как раз и дает сложение. Вспомните из математики: минус на минус дает плюс

```
3 - -2; // 5
```
