### ISSUE TITLE
Неизвестно где ставить кавычки так как он их ставит сам неправильно в тестах

### ISSUE THREAD

**Issue by FallenStarrr** [hexlet-basics/exercises-java#241]
https://code-basics.com/ru/languages/java/lessons/quotes#editor

**Comment by ssssank** [comment]
@Malcom1986 глянь, плиз

**Comment by Malcom1986** [comment]
@FallenStarrr Приветствую! Кавычки нужно расставить таким образом, чтобы на экран вывелась фраза, в точности так, как в примере. Тесты проверяют только соответствие ожидаемой фразы и того, что вывелось фактически, кавычки он не ставят
