### ISSUE TITLE
[Error] Variable name spelling error.

### ISSUE THREAD

**Issue by laflenory** [hexlet-basics/exercises-java#255]
```
Для имени переменной используется любой набор допустимых символов, к которым относятся буквы английского алфавита, цифры, знаки - и _. 
``` 

[Click](https://code-basics.com/ru/languages/java/lessons/definition)

**Comment by laflenory** [comment]
знак '-' в имени переменной приводит к ошибке компиляции.

```shell
$ java Application.java
Application.java:3: error: not a statement
        int -first_number = 0;
        ^
Application.java:3: error: ';' expected
        int -first_number = 0;
           ^
2 errors
error: compilation failed
```

**Comment by laflenory** [comment]
[description.ru.yml](https://github.com/hexlet-basics/exercises-java/blob/main/modules/30-variables/10-definition/description.ru.yml)
[description.en.yml](https://github.com/hexlet-basics/exercises-java/blob/main/modules/30-variables/10-definition/description.en.yml)

строка 32.

**Comment by Malcom1986** [comment]
Спасибо, поправил
