### ISSUE TITLE
Не выводится содержимое System.out.print() при решении заданий курса Java

### ISSUE THREAD

**Issue by unsigable** [hexlet-basics/exercises-java#278]
## Описание ошибки:    
*из курса по Java*

При решении заданий в поле "Вывод" не выводится содержимое System.out.print(), в отличие от System.out.println() - хотя решение принимается и проходит проверку!

![cb-bug_input](https://github.com/user-attachments/assets/485856d2-de54-4a9b-975a-dcd88ae94aeb)

![cb-bug_output](https://github.com/user-attachments/assets/0ef239cf-a36d-4901-88f5-38091ce07bac)

В данном случае, требуется вывести на экран две строки.   
- при выводе первой строки используется System.out.println();
- при выводе второй строки используется System.out.print(); <<< для демонстрации бага    

***Ожидаемый результат:***
- Вывод двух строк.  
``` shell
15
2
```

***Фактический результат:***
- Вывод только одной строки - где используется System.out.println();
``` shell
15
```

**Comment by fey** [comment]
@unsigable я черенес в java

**Comment by unsigable** [comment]
Сделал несколько правок для простых тестов.

**Comment by unsigable** [comment]
Внес правки для устранения:

```
exercises-1  | Test.java:17: error: cannot find symbol
exercises-1  |         System.setOut(new PrintStream(new FileOutputStream(FileDescriptor.out)));
exercises-1  |   symbol:   variable FileDescriptor
exercises-1  |   location: class Test
exercises-1  | 2 errors
```

**Comment by unsigable** [comment]
Проверил измененные файлы на наличие 'import java.io.FileDescriptor;' и внес изменения еще в 2 урока с простым однострочным выводом (38-й и 39-й)

**Comment by Malcom1986** [comment]
@unsigable  Привет! Фиксить нужно только в тех практиках, где есть вывод на экран. Там в тестах мы перехватываем этот вывод проверяем его. То есть это на первый взляд все практики до урока про возврат значений из методов. Дальше уже нет никакого вывода, мы проверяем непосредственно значение, которое вернул метод. Там уже править ничего не нужно, так как вывода нет

**Comment by unsigable** [comment]
@Malcom1986 Спасибо за комментарий!
Мне нужно внести какие-то изменения?
Прошу прощение за сбой при запуске проверки из-за подтверждением почты! (я не понял почему так произошло)

**Comment by unsigable** [comment]
@Malcom1986 что-то еще нужно исправить в рамках данного issue или закрыть его ?

**Comment by Malcom1986** [comment]
Добрый день! Можно закрывать, да. ПР смержили, который решал эту задачу
