### ISSUE TITLE
Задание 40/77

### ISSUE THREAD

**Issue by Draught707** [hexlet-basics/exercises-java#90]
Из текста задания:

const distance = calculateDistanceBetweenTowns('Lannisport-Bayasabhad');

const from = 'The Twins';
const to = 'The Eyrie';

Верное решение:

const distance = calculateDistanceBetweenTowns(`${from}-${to}`);

Но ${from} это The Twins, а ${to} это The Eyrie.

Поэтому (`${from}-${to}`) это (The Twins-The Eyrie). Хотя функция calculateDistanceBetweenTowns требует ('The Twins-The Eyrie'), с апострофами.

Просится тогда решение ('`${from}-${to}`').
Почему не так? Спасибо!

**Comment by samokisha** [comment]
Issue не в том репозитории. Issue относиться к [hexlet-basics/exercises-javascript](https://github.com/hexlet-basics/exercises-javascript).
